dataset:
  data_path: /home/alex/Documents/Project_CDT/GRAN_social/data
  dev_ratio: 0.2
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: social
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 1
  train_ratio: 0.8
device: cuda
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_social_2022-Jun-27-09-52-31_367733
generate:
  batch_size: 4
  better_vis: true
  is_eval: true
  is_single_plot: true
  is_vis: true
  num_test_gen: 12
  num_vis: 12
  num_workers: 6
  test_model_dir: /home/alex/Documents/Project_CDT/GRAN_social/exp/GRAN/FACEBOOK_LARGE
  test_model_name: model_snapshot_0020000.pth
  vis_num_row: 4
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 256
  has_attention: true
  hidden_dim: 256
  is_sym: true
  max_num_nodes: 801
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
run_id: '367733'
runner: GranRunner
save_dir: /home/alex/Documents/Project_CDT/GRAN_social/exp/GRAN/FACEBOOK_LARGE
seed: 4454
test:
  batch_size: 4
  better_vis: true
  is_single_plot: true
  is_test_ER: false
  is_vis: true
  num_test_gen: 4
  num_vis: 12
  num_workers: 6
  test_model_dir: /home/alex/Documents/Project_CDT/GRAN_social/exp/GRAN/FACEBOOK_LARGE
  test_model_name: model_snapshot_0020000.pth
  vis_num_row: 4
train:
  batch_size: 5
  display_iter: 5
  is_resume: true
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 40
  max_epoch: 20000
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: /home/alex/Documents/Project_CDT/GRAN_social/exp/GRAN/FACEBOOK_LARGE
  resume_epoch: 20000
  resume_model: model_snapshot_0020000.pth
  shuffle: true
  snapshot_epoch: 50
  valid_epoch: 10
  wd: 0.0
use_gpu: true
use_horovod: false
