---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda
gpus: [0]
seed: 4454
dataset:
  loader_name: GRANData
  name: FACEBOOK
  data_path: /home/alex/Projects/GRAN_social/data
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 1 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: true
model:
  name: GRANMixtureBernoulli
  num_mix_component: 20
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 201
  hidden_dim: 256
  embedding_dim: 256
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_epoch: [40] # no decay
  num_workers: 0
  max_epoch: 35000
  batch_size: 40
  display_iter: 15
  snapshot_epoch: 500
  valid_epoch: 10
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: true
  resume_epoch: 10000
  resume_dir: /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK
  resume_model: model_snapshot_0010000.pth
test:
  batch_size: 4
  num_workers: 6
  num_test_gen: 40 # number of generated samples
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 9
  vis_num_row: 3 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK
  test_model_name: model_snapshot_0010000.pth
generate:
  batch_size: 10
  num_workers: 12
  num_test_gen: 100 # number of generated samples
  is_eval: true
  is_eval_rmat: true
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  num_vis: 8
  vis_num_row: 3 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK
  test_model_name: model_snapshot_0010000.pth
