dataset:
  data_path: /home/alex/Projects/GRAN_social/data
  dev_ratio: 0.2
  has_node_feat: true
  is_overwrite_precompute: true
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: FACEBOOK_LARGE
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 1
  train_ratio: 0.8
device: cuda
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_FACEBOOK_LARGE_2022-Jul-01-11-19-50_62653
generate:
  batch_size: 4
  better_vis: true
  is_eval: true
  is_single_plot: true
  is_vis: true
  num_test_gen: 40
  num_vis: 12
  num_workers: 12
  test_model_dir: /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK_LARGE_ATTRIBUTED
  test_model_name: model_snapshot_0000340.pth
  vis_num_row: 4
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 256
  has_attention: true
  hidden_dim: 256
  is_sym: true
  max_num_nodes: 501
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 2
run_id: '62653'
runner: GranRunner
save_dir: exp/GRAN/GRANMixtureBernoulli_FACEBOOK_LARGE_2022-Jul-01-11-19-50_62653
seed: 4454
test:
  batch_size: 4
  better_vis: true
  is_single_plot: true
  is_test_ER: false
  is_vis: true
  num_test_gen: 12
  num_vis: 12
  num_workers: 6
  test_model_dir: exp/GRAN/GRANMixtureBernoulli_FACEBOOK_LARGE_2022-Jul-01-11-19-50_62653
  test_model_name: model_snapshot_0000120.pth
  vis_num_row: 4
train:
  batch_size: 10
  display_iter: 15
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 40
  max_epoch: 35000
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK_LARGE_ATTRIBUTED
  resume_epoch: 340
  resume_model: model_snapshot_0000340.pth
  shuffle: true
  snapshot_epoch: 20
  valid_epoch: 10
  wd: 0.0
use_gpu: true
use_horovod: false
